# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: achievement.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='achievement.proto',
  package='Sanguo.protocol.achievement',
  serialized_pb='\n\x11\x61\x63hievement.proto\x12\x1bSanguo.protocol.achievement\"\x9d\x04\n\x0b\x41\x63hievement\x12\n\n\x02id\x18\x01 \x02(\x05\x12I\n\x04mach\x18\x02 \x01(\x0b\x32;.Sanguo.protocol.achievement.Achievement.MultiIDAchievement\x12J\n\x04sach\x18\x03 \x01(\x0b\x32<.Sanguo.protocol.achievement.Achievement.SingleIDAchievement\x12I\n\x04\x63\x61\x63h\x18\x04 \x01(\x0b\x32;.Sanguo.protocol.achievement.Achievement.CounterAchievement\x12I\n\x06status\x18\x05 \x02(\x0e\x32\x39.Sanguo.protocol.achievement.Achievement.AchivementStatus\x1a\x38\n\x12MultiIDAchievement\x12\x0f\n\x07\x63urrent\x18\x01 \x03(\x05\x12\x11\n\tcondition\x18\x02 \x03(\x05\x1a(\n\x13SingleIDAchievement\x12\x11\n\tcondition\x18\x01 \x02(\x05\x1a\x38\n\x12\x43ounterAchievement\x12\x0f\n\x07\x63urrent\x18\x01 \x02(\x05\x12\x11\n\tcondition\x18\x02 \x02(\x05\"7\n\x10\x41\x63hivementStatus\x12\t\n\x05\x44OING\x10\x01\x12\n\n\x06REWARD\x10\x02\x12\x0c\n\x08\x43OMPLETE\x10\x03\"d\n\x11\x41\x63hievementNotify\x12\x0f\n\x07session\x18\x01 \x02(\x0c\x12>\n\x0c\x61\x63hievements\x18\x02 \x03(\x0b\x32(.Sanguo.protocol.achievement.Achievement\"i\n\x17UpdateAchievementNotify\x12\x0f\n\x07session\x18\x01 \x02(\x0c\x12=\n\x0b\x61\x63hievement\x18\x02 \x02(\x0b\x32(.Sanguo.protocol.achievement.Achievement\"f\n\x14\x41\x64\x64\x41\x63hievementNotify\x12\x0f\n\x07session\x18\x01 \x02(\x0c\x12=\n\x0b\x61\x63hievement\x18\x02 \x02(\x0b\x32(.Sanguo.protocol.achievement.Achievement\"6\n\x17RemoveAchievementNotify\x12\x0f\n\x07session\x18\x01 \x02(\x0c\x12\n\n\x02id\x18\x02 \x02(\x05\":\n\x1b\x41\x63hievementGetRewardRequest\x12\x0f\n\x07session\x18\x01 \x02(\x0c\x12\n\n\x02id\x18\x02 \x02(\x05\"<\n\x1c\x41\x63hievementGetRewardResponse\x12\x0b\n\x03ret\x18\x01 \x02(\x05\x12\x0f\n\x07session\x18\x02 \x02(\x0c')



_ACHIEVEMENT_ACHIVEMENTSTATUS = _descriptor.EnumDescriptor(
  name='AchivementStatus',
  full_name='Sanguo.protocol.achievement.Achievement.AchivementStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DOING', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REWARD', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMPLETE', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=537,
  serialized_end=592,
)


_ACHIEVEMENT_MULTIIDACHIEVEMENT = _descriptor.Descriptor(
  name='MultiIDAchievement',
  full_name='Sanguo.protocol.achievement.Achievement.MultiIDAchievement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='current', full_name='Sanguo.protocol.achievement.Achievement.MultiIDAchievement.current', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='condition', full_name='Sanguo.protocol.achievement.Achievement.MultiIDAchievement.condition', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=379,
  serialized_end=435,
)

_ACHIEVEMENT_SINGLEIDACHIEVEMENT = _descriptor.Descriptor(
  name='SingleIDAchievement',
  full_name='Sanguo.protocol.achievement.Achievement.SingleIDAchievement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='condition', full_name='Sanguo.protocol.achievement.Achievement.SingleIDAchievement.condition', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=437,
  serialized_end=477,
)

_ACHIEVEMENT_COUNTERACHIEVEMENT = _descriptor.Descriptor(
  name='CounterAchievement',
  full_name='Sanguo.protocol.achievement.Achievement.CounterAchievement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='current', full_name='Sanguo.protocol.achievement.Achievement.CounterAchievement.current', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='condition', full_name='Sanguo.protocol.achievement.Achievement.CounterAchievement.condition', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=479,
  serialized_end=535,
)

_ACHIEVEMENT = _descriptor.Descriptor(
  name='Achievement',
  full_name='Sanguo.protocol.achievement.Achievement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Sanguo.protocol.achievement.Achievement.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mach', full_name='Sanguo.protocol.achievement.Achievement.mach', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sach', full_name='Sanguo.protocol.achievement.Achievement.sach', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cach', full_name='Sanguo.protocol.achievement.Achievement.cach', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='Sanguo.protocol.achievement.Achievement.status', index=4,
      number=5, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_ACHIEVEMENT_MULTIIDACHIEVEMENT, _ACHIEVEMENT_SINGLEIDACHIEVEMENT, _ACHIEVEMENT_COUNTERACHIEVEMENT, ],
  enum_types=[
    _ACHIEVEMENT_ACHIVEMENTSTATUS,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=51,
  serialized_end=592,
)


_ACHIEVEMENTNOTIFY = _descriptor.Descriptor(
  name='AchievementNotify',
  full_name='Sanguo.protocol.achievement.AchievementNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='session', full_name='Sanguo.protocol.achievement.AchievementNotify.session', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='achievements', full_name='Sanguo.protocol.achievement.AchievementNotify.achievements', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=594,
  serialized_end=694,
)


_UPDATEACHIEVEMENTNOTIFY = _descriptor.Descriptor(
  name='UpdateAchievementNotify',
  full_name='Sanguo.protocol.achievement.UpdateAchievementNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='session', full_name='Sanguo.protocol.achievement.UpdateAchievementNotify.session', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='achievement', full_name='Sanguo.protocol.achievement.UpdateAchievementNotify.achievement', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=696,
  serialized_end=801,
)


_ADDACHIEVEMENTNOTIFY = _descriptor.Descriptor(
  name='AddAchievementNotify',
  full_name='Sanguo.protocol.achievement.AddAchievementNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='session', full_name='Sanguo.protocol.achievement.AddAchievementNotify.session', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='achievement', full_name='Sanguo.protocol.achievement.AddAchievementNotify.achievement', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=803,
  serialized_end=905,
)


_REMOVEACHIEVEMENTNOTIFY = _descriptor.Descriptor(
  name='RemoveAchievementNotify',
  full_name='Sanguo.protocol.achievement.RemoveAchievementNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='session', full_name='Sanguo.protocol.achievement.RemoveAchievementNotify.session', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='Sanguo.protocol.achievement.RemoveAchievementNotify.id', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=907,
  serialized_end=961,
)


_ACHIEVEMENTGETREWARDREQUEST = _descriptor.Descriptor(
  name='AchievementGetRewardRequest',
  full_name='Sanguo.protocol.achievement.AchievementGetRewardRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='session', full_name='Sanguo.protocol.achievement.AchievementGetRewardRequest.session', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='Sanguo.protocol.achievement.AchievementGetRewardRequest.id', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=963,
  serialized_end=1021,
)


_ACHIEVEMENTGETREWARDRESPONSE = _descriptor.Descriptor(
  name='AchievementGetRewardResponse',
  full_name='Sanguo.protocol.achievement.AchievementGetRewardResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret', full_name='Sanguo.protocol.achievement.AchievementGetRewardResponse.ret', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='session', full_name='Sanguo.protocol.achievement.AchievementGetRewardResponse.session', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=1023,
  serialized_end=1083,
)

_ACHIEVEMENT_MULTIIDACHIEVEMENT.containing_type = _ACHIEVEMENT;
_ACHIEVEMENT_SINGLEIDACHIEVEMENT.containing_type = _ACHIEVEMENT;
_ACHIEVEMENT_COUNTERACHIEVEMENT.containing_type = _ACHIEVEMENT;
_ACHIEVEMENT.fields_by_name['mach'].message_type = _ACHIEVEMENT_MULTIIDACHIEVEMENT
_ACHIEVEMENT.fields_by_name['sach'].message_type = _ACHIEVEMENT_SINGLEIDACHIEVEMENT
_ACHIEVEMENT.fields_by_name['cach'].message_type = _ACHIEVEMENT_COUNTERACHIEVEMENT
_ACHIEVEMENT.fields_by_name['status'].enum_type = _ACHIEVEMENT_ACHIVEMENTSTATUS
_ACHIEVEMENT_ACHIVEMENTSTATUS.containing_type = _ACHIEVEMENT;
_ACHIEVEMENTNOTIFY.fields_by_name['achievements'].message_type = _ACHIEVEMENT
_UPDATEACHIEVEMENTNOTIFY.fields_by_name['achievement'].message_type = _ACHIEVEMENT
_ADDACHIEVEMENTNOTIFY.fields_by_name['achievement'].message_type = _ACHIEVEMENT
DESCRIPTOR.message_types_by_name['Achievement'] = _ACHIEVEMENT
DESCRIPTOR.message_types_by_name['AchievementNotify'] = _ACHIEVEMENTNOTIFY
DESCRIPTOR.message_types_by_name['UpdateAchievementNotify'] = _UPDATEACHIEVEMENTNOTIFY
DESCRIPTOR.message_types_by_name['AddAchievementNotify'] = _ADDACHIEVEMENTNOTIFY
DESCRIPTOR.message_types_by_name['RemoveAchievementNotify'] = _REMOVEACHIEVEMENTNOTIFY
DESCRIPTOR.message_types_by_name['AchievementGetRewardRequest'] = _ACHIEVEMENTGETREWARDREQUEST
DESCRIPTOR.message_types_by_name['AchievementGetRewardResponse'] = _ACHIEVEMENTGETREWARDRESPONSE

class Achievement(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class MultiIDAchievement(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _ACHIEVEMENT_MULTIIDACHIEVEMENT

    # @@protoc_insertion_point(class_scope:Sanguo.protocol.achievement.Achievement.MultiIDAchievement)

  class SingleIDAchievement(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _ACHIEVEMENT_SINGLEIDACHIEVEMENT

    # @@protoc_insertion_point(class_scope:Sanguo.protocol.achievement.Achievement.SingleIDAchievement)

  class CounterAchievement(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _ACHIEVEMENT_COUNTERACHIEVEMENT

    # @@protoc_insertion_point(class_scope:Sanguo.protocol.achievement.Achievement.CounterAchievement)
  DESCRIPTOR = _ACHIEVEMENT

  # @@protoc_insertion_point(class_scope:Sanguo.protocol.achievement.Achievement)

class AchievementNotify(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ACHIEVEMENTNOTIFY

  # @@protoc_insertion_point(class_scope:Sanguo.protocol.achievement.AchievementNotify)

class UpdateAchievementNotify(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _UPDATEACHIEVEMENTNOTIFY

  # @@protoc_insertion_point(class_scope:Sanguo.protocol.achievement.UpdateAchievementNotify)

class AddAchievementNotify(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ADDACHIEVEMENTNOTIFY

  # @@protoc_insertion_point(class_scope:Sanguo.protocol.achievement.AddAchievementNotify)

class RemoveAchievementNotify(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REMOVEACHIEVEMENTNOTIFY

  # @@protoc_insertion_point(class_scope:Sanguo.protocol.achievement.RemoveAchievementNotify)

class AchievementGetRewardRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ACHIEVEMENTGETREWARDREQUEST

  # @@protoc_insertion_point(class_scope:Sanguo.protocol.achievement.AchievementGetRewardRequest)

class AchievementGetRewardResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ACHIEVEMENTGETREWARDRESPONSE

  # @@protoc_insertion_point(class_scope:Sanguo.protocol.achievement.AchievementGetRewardResponse)


# @@protoc_insertion_point(module_scope)
