# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='common.proto',
  package='Sanguo.protocol.common',
  serialized_pb='\n\x0c\x63ommon.proto\x12\x16Sanguo.protocol.common\"7\n\x0eHeroInfomation\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0b\n\x03oid\x18\x02 \x02(\x05\x12\x0c\n\x04step\x18\x03 \x02(\x05\"\xa5\x01\n\x13\x43haracterInfomation\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0c\n\x04name\x18\x02 \x02(\t\x12\r\n\x05level\x18\x03 \x02(\x05\x12\x0b\n\x03vip\x18\x04 \x02(\x05\x12\r\n\x05power\x18\x05 \x02(\x05\x12\x39\n\tformation\x18\x06 \x03(\x0b\x32&.Sanguo.protocol.common.HeroInfomation\x12\x0e\n\x06leader\x18\x07 \x02(\x05')




_HEROINFOMATION = _descriptor.Descriptor(
  name='HeroInfomation',
  full_name='Sanguo.protocol.common.HeroInfomation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Sanguo.protocol.common.HeroInfomation.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='oid', full_name='Sanguo.protocol.common.HeroInfomation.oid', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='step', full_name='Sanguo.protocol.common.HeroInfomation.step', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=40,
  serialized_end=95,
)


_CHARACTERINFOMATION = _descriptor.Descriptor(
  name='CharacterInfomation',
  full_name='Sanguo.protocol.common.CharacterInfomation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Sanguo.protocol.common.CharacterInfomation.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='Sanguo.protocol.common.CharacterInfomation.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='level', full_name='Sanguo.protocol.common.CharacterInfomation.level', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vip', full_name='Sanguo.protocol.common.CharacterInfomation.vip', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='power', full_name='Sanguo.protocol.common.CharacterInfomation.power', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='formation', full_name='Sanguo.protocol.common.CharacterInfomation.formation', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='leader', full_name='Sanguo.protocol.common.CharacterInfomation.leader', index=6,
      number=7, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=98,
  serialized_end=263,
)

_CHARACTERINFOMATION.fields_by_name['formation'].message_type = _HEROINFOMATION
DESCRIPTOR.message_types_by_name['HeroInfomation'] = _HEROINFOMATION
DESCRIPTOR.message_types_by_name['CharacterInfomation'] = _CHARACTERINFOMATION

class HeroInfomation(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HEROINFOMATION

  # @@protoc_insertion_point(class_scope:Sanguo.protocol.common.HeroInfomation)

class CharacterInfomation(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CHARACTERINFOMATION

  # @@protoc_insertion_point(class_scope:Sanguo.protocol.common.CharacterInfomation)


# @@protoc_insertion_point(module_scope)
