# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: daily.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='daily.proto',
  package='Sanguo.protocol.daily',
  serialized_pb='\n\x0b\x64\x61ily.proto\x12\x15Sanguo.protocol.daily\"\xb3\x01\n\rCheckInNotify\x12\x0f\n\x07session\x18\x01 \x02(\x0c\x12<\n\x02tp\x18\x02 \x03(\x0b\x32\x30.Sanguo.protocol.daily.CheckInNotify.CheckInType\x12\x14\n\x0c\x63heckin_days\x18\x03 \x03(\x05\x1a=\n\x0b\x43heckInType\x12\n\n\x02tp\x18\x01 \x02(\x05\x12\x10\n\x08\x63omplete\x18\x02 \x02(\x08\x12\x10\n\x08\x66inished\x18\x03 \x02(\x08\"!\n\x0e\x43heckInRequest\x12\x0f\n\x07session\x18\x01 \x02(\x0c\"/\n\x0f\x43heckInResponse\x12\x0b\n\x03ret\x18\x01 \x02(\x05\x12\x0f\n\x07session\x18\x02 \x02(\x0c\"6\n\x17GetCheckInRewardRequest\x12\x0f\n\x07session\x18\x01 \x02(\x0c\x12\n\n\x02tp\x18\x02 \x02(\x05\"8\n\x18GetCheckInRewardResponse\x12\x0b\n\x03ret\x18\x01 \x02(\x05\x12\x0f\n\x07session\x18\x02 \x02(\x0c')




_CHECKINNOTIFY_CHECKINTYPE = _descriptor.Descriptor(
  name='CheckInType',
  full_name='Sanguo.protocol.daily.CheckInNotify.CheckInType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tp', full_name='Sanguo.protocol.daily.CheckInNotify.CheckInType.tp', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='complete', full_name='Sanguo.protocol.daily.CheckInNotify.CheckInType.complete', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='finished', full_name='Sanguo.protocol.daily.CheckInNotify.CheckInType.finished', index=2,
      number=3, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=157,
  serialized_end=218,
)

_CHECKINNOTIFY = _descriptor.Descriptor(
  name='CheckInNotify',
  full_name='Sanguo.protocol.daily.CheckInNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='session', full_name='Sanguo.protocol.daily.CheckInNotify.session', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tp', full_name='Sanguo.protocol.daily.CheckInNotify.tp', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='checkin_days', full_name='Sanguo.protocol.daily.CheckInNotify.checkin_days', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_CHECKINNOTIFY_CHECKINTYPE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=39,
  serialized_end=218,
)


_CHECKINREQUEST = _descriptor.Descriptor(
  name='CheckInRequest',
  full_name='Sanguo.protocol.daily.CheckInRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='session', full_name='Sanguo.protocol.daily.CheckInRequest.session', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=220,
  serialized_end=253,
)


_CHECKINRESPONSE = _descriptor.Descriptor(
  name='CheckInResponse',
  full_name='Sanguo.protocol.daily.CheckInResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret', full_name='Sanguo.protocol.daily.CheckInResponse.ret', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='session', full_name='Sanguo.protocol.daily.CheckInResponse.session', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=255,
  serialized_end=302,
)


_GETCHECKINREWARDREQUEST = _descriptor.Descriptor(
  name='GetCheckInRewardRequest',
  full_name='Sanguo.protocol.daily.GetCheckInRewardRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='session', full_name='Sanguo.protocol.daily.GetCheckInRewardRequest.session', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tp', full_name='Sanguo.protocol.daily.GetCheckInRewardRequest.tp', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=304,
  serialized_end=358,
)


_GETCHECKINREWARDRESPONSE = _descriptor.Descriptor(
  name='GetCheckInRewardResponse',
  full_name='Sanguo.protocol.daily.GetCheckInRewardResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret', full_name='Sanguo.protocol.daily.GetCheckInRewardResponse.ret', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='session', full_name='Sanguo.protocol.daily.GetCheckInRewardResponse.session', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=360,
  serialized_end=416,
)

_CHECKINNOTIFY_CHECKINTYPE.containing_type = _CHECKINNOTIFY;
_CHECKINNOTIFY.fields_by_name['tp'].message_type = _CHECKINNOTIFY_CHECKINTYPE
DESCRIPTOR.message_types_by_name['CheckInNotify'] = _CHECKINNOTIFY
DESCRIPTOR.message_types_by_name['CheckInRequest'] = _CHECKINREQUEST
DESCRIPTOR.message_types_by_name['CheckInResponse'] = _CHECKINRESPONSE
DESCRIPTOR.message_types_by_name['GetCheckInRewardRequest'] = _GETCHECKINREWARDREQUEST
DESCRIPTOR.message_types_by_name['GetCheckInRewardResponse'] = _GETCHECKINREWARDRESPONSE

class CheckInNotify(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class CheckInType(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _CHECKINNOTIFY_CHECKINTYPE

    # @@protoc_insertion_point(class_scope:Sanguo.protocol.daily.CheckInNotify.CheckInType)
  DESCRIPTOR = _CHECKINNOTIFY

  # @@protoc_insertion_point(class_scope:Sanguo.protocol.daily.CheckInNotify)

class CheckInRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CHECKINREQUEST

  # @@protoc_insertion_point(class_scope:Sanguo.protocol.daily.CheckInRequest)

class CheckInResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CHECKINRESPONSE

  # @@protoc_insertion_point(class_scope:Sanguo.protocol.daily.CheckInResponse)

class GetCheckInRewardRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETCHECKINREWARDREQUEST

  # @@protoc_insertion_point(class_scope:Sanguo.protocol.daily.GetCheckInRewardRequest)

class GetCheckInRewardResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GETCHECKINREWARDRESPONSE

  # @@protoc_insertion_point(class_scope:Sanguo.protocol.daily.GetCheckInRewardResponse)


# @@protoc_insertion_point(module_scope)
