# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: daily.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import world_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='daily.proto',
  package='Sanguo.protocol.daily',
  serialized_pb='\n\x0b\x64\x61ily.proto\x12\x15Sanguo.protocol.daily\x1a\x0bworld.proto\"Q\n\rCheckInNotify\x12\x0f\n\x07session\x18\x01 \x02(\x0c\x12\x0f\n\x07\x63heckin\x18\x02 \x02(\x08\x12\x0c\n\x04\x64\x61ys\x18\x03 \x02(\x05\x12\x10\n\x08max_days\x18\x04 \x02(\x05\"!\n\x0e\x43heckInRequest\x12\x0f\n\x07session\x18\x01 \x02(\x0c\"b\n\x0f\x43heckInResponse\x12\x0b\n\x03ret\x18\x01 \x02(\x05\x12\x0f\n\x07session\x18\x02 \x02(\x0c\x12\x31\n\x06reward\x18\x03 \x01(\x0b\x32!.Sanguo.protocol.world.Attachment')




_CHECKINNOTIFY = _descriptor.Descriptor(
  name='CheckInNotify',
  full_name='Sanguo.protocol.daily.CheckInNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='session', full_name='Sanguo.protocol.daily.CheckInNotify.session', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='checkin', full_name='Sanguo.protocol.daily.CheckInNotify.checkin', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='days', full_name='Sanguo.protocol.daily.CheckInNotify.days', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_days', full_name='Sanguo.protocol.daily.CheckInNotify.max_days', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=51,
  serialized_end=132,
)


_CHECKINREQUEST = _descriptor.Descriptor(
  name='CheckInRequest',
  full_name='Sanguo.protocol.daily.CheckInRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='session', full_name='Sanguo.protocol.daily.CheckInRequest.session', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=134,
  serialized_end=167,
)


_CHECKINRESPONSE = _descriptor.Descriptor(
  name='CheckInResponse',
  full_name='Sanguo.protocol.daily.CheckInResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret', full_name='Sanguo.protocol.daily.CheckInResponse.ret', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='session', full_name='Sanguo.protocol.daily.CheckInResponse.session', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reward', full_name='Sanguo.protocol.daily.CheckInResponse.reward', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=169,
  serialized_end=267,
)

_CHECKINRESPONSE.fields_by_name['reward'].message_type = world_pb2._ATTACHMENT
DESCRIPTOR.message_types_by_name['CheckInNotify'] = _CHECKINNOTIFY
DESCRIPTOR.message_types_by_name['CheckInRequest'] = _CHECKINREQUEST
DESCRIPTOR.message_types_by_name['CheckInResponse'] = _CHECKINRESPONSE

class CheckInNotify(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CHECKINNOTIFY

  # @@protoc_insertion_point(class_scope:Sanguo.protocol.daily.CheckInNotify)

class CheckInRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CHECKINREQUEST

  # @@protoc_insertion_point(class_scope:Sanguo.protocol.daily.CheckInRequest)

class CheckInResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CHECKINRESPONSE

  # @@protoc_insertion_point(class_scope:Sanguo.protocol.daily.CheckInResponse)


# @@protoc_insertion_point(module_scope)
