# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: formation.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='formation.proto',
  package='Sanguo.protocol.formation',
  serialized_pb='\n\x0f\x66ormation.proto\x12\x19Sanguo.protocol.formation\"8\n\x08Position\x12\x0b\n\x03pos\x18\x01 \x02(\x05\x12\x0e\n\x06\x65nable\x18\x02 \x01(\x08\x12\x0f\n\x07hero_id\x18\x03 \x01(\x05\"C\n\tFormation\x12\x36\n\tpositions\x18\x01 \x03(\x0b\x32#.Sanguo.protocol.formation.Position\"^\n\x13SetFormationRequest\x12\x0f\n\x07session\x18\x01 \x02(\t\x12\x36\n\tpositions\x18\x02 \x03(\x0b\x32#.Sanguo.protocol.formation.Position\"4\n\x14SetFormationResponse\x12\x0b\n\x03ret\x18\x01 \x02(\x05\x12\x0f\n\x07session\x18\x02 \x02(\t\"[\n\x0f\x46ormationNotify\x12\x0f\n\x07session\x18\x01 \x02(\t\x12\x37\n\tformation\x18\x02 \x02(\x0b\x32$.Sanguo.protocol.formation.Formation')




_POSITION = _descriptor.Descriptor(
  name='Position',
  full_name='Sanguo.protocol.formation.Position',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pos', full_name='Sanguo.protocol.formation.Position.pos', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='enable', full_name='Sanguo.protocol.formation.Position.enable', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hero_id', full_name='Sanguo.protocol.formation.Position.hero_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=46,
  serialized_end=102,
)


_FORMATION = _descriptor.Descriptor(
  name='Formation',
  full_name='Sanguo.protocol.formation.Formation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='positions', full_name='Sanguo.protocol.formation.Formation.positions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=104,
  serialized_end=171,
)


_SETFORMATIONREQUEST = _descriptor.Descriptor(
  name='SetFormationRequest',
  full_name='Sanguo.protocol.formation.SetFormationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='session', full_name='Sanguo.protocol.formation.SetFormationRequest.session', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='positions', full_name='Sanguo.protocol.formation.SetFormationRequest.positions', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=173,
  serialized_end=267,
)


_SETFORMATIONRESPONSE = _descriptor.Descriptor(
  name='SetFormationResponse',
  full_name='Sanguo.protocol.formation.SetFormationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret', full_name='Sanguo.protocol.formation.SetFormationResponse.ret', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='session', full_name='Sanguo.protocol.formation.SetFormationResponse.session', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=269,
  serialized_end=321,
)


_FORMATIONNOTIFY = _descriptor.Descriptor(
  name='FormationNotify',
  full_name='Sanguo.protocol.formation.FormationNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='session', full_name='Sanguo.protocol.formation.FormationNotify.session', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='formation', full_name='Sanguo.protocol.formation.FormationNotify.formation', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=323,
  serialized_end=414,
)

_FORMATION.fields_by_name['positions'].message_type = _POSITION
_SETFORMATIONREQUEST.fields_by_name['positions'].message_type = _POSITION
_FORMATIONNOTIFY.fields_by_name['formation'].message_type = _FORMATION
DESCRIPTOR.message_types_by_name['Position'] = _POSITION
DESCRIPTOR.message_types_by_name['Formation'] = _FORMATION
DESCRIPTOR.message_types_by_name['SetFormationRequest'] = _SETFORMATIONREQUEST
DESCRIPTOR.message_types_by_name['SetFormationResponse'] = _SETFORMATIONRESPONSE
DESCRIPTOR.message_types_by_name['FormationNotify'] = _FORMATIONNOTIFY

class Position(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _POSITION

  # @@protoc_insertion_point(class_scope:Sanguo.protocol.formation.Position)

class Formation(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FORMATION

  # @@protoc_insertion_point(class_scope:Sanguo.protocol.formation.Formation)

class SetFormationRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SETFORMATIONREQUEST

  # @@protoc_insertion_point(class_scope:Sanguo.protocol.formation.SetFormationRequest)

class SetFormationResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SETFORMATIONRESPONSE

  # @@protoc_insertion_point(class_scope:Sanguo.protocol.formation.SetFormationResponse)

class FormationNotify(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FORMATIONNOTIFY

  # @@protoc_insertion_point(class_scope:Sanguo.protocol.formation.FormationNotify)


# @@protoc_insertion_point(module_scope)
