# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: prize.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import world_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='prize.proto',
  package='Sanguo.protocol.prize',
  serialized_pb='\n\x0bprize.proto\x12\x15Sanguo.protocol.prize\x1a\x0bworld.proto\"1\n\x0bPrizeNotify\x12\x0f\n\x07session\x18\x01 \x02(\x0c\x12\x11\n\tprize_ids\x18\x02 \x03(\x05\"1\n\x0cPrizeRequest\x12\x0f\n\x07session\x18\x01 \x02(\x0c\x12\x10\n\x08prize_id\x18\x02 \x02(\x05\"j\n\rPrizeResponse\x12\x0b\n\x03ret\x18\x01 \x02(\x05\x12\x0f\n\x07session\x18\x02 \x02(\x0c\x12\x10\n\x08prize_id\x18\x03 \x01(\x05\x12)\n\x04\x64rop\x18\x04 \x01(\x0b\x32\x1b.Sanguo.protocol.world.Drop')




_PRIZENOTIFY = _descriptor.Descriptor(
  name='PrizeNotify',
  full_name='Sanguo.protocol.prize.PrizeNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='session', full_name='Sanguo.protocol.prize.PrizeNotify.session', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='prize_ids', full_name='Sanguo.protocol.prize.PrizeNotify.prize_ids', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=51,
  serialized_end=100,
)


_PRIZEREQUEST = _descriptor.Descriptor(
  name='PrizeRequest',
  full_name='Sanguo.protocol.prize.PrizeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='session', full_name='Sanguo.protocol.prize.PrizeRequest.session', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='prize_id', full_name='Sanguo.protocol.prize.PrizeRequest.prize_id', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=102,
  serialized_end=151,
)


_PRIZERESPONSE = _descriptor.Descriptor(
  name='PrizeResponse',
  full_name='Sanguo.protocol.prize.PrizeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret', full_name='Sanguo.protocol.prize.PrizeResponse.ret', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='session', full_name='Sanguo.protocol.prize.PrizeResponse.session', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='prize_id', full_name='Sanguo.protocol.prize.PrizeResponse.prize_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='drop', full_name='Sanguo.protocol.prize.PrizeResponse.drop', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=153,
  serialized_end=259,
)

_PRIZERESPONSE.fields_by_name['drop'].message_type = world_pb2._DROP
DESCRIPTOR.message_types_by_name['PrizeNotify'] = _PRIZENOTIFY
DESCRIPTOR.message_types_by_name['PrizeRequest'] = _PRIZEREQUEST
DESCRIPTOR.message_types_by_name['PrizeResponse'] = _PRIZERESPONSE

class PrizeNotify(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PRIZENOTIFY

  # @@protoc_insertion_point(class_scope:Sanguo.protocol.prize.PrizeNotify)

class PrizeRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PRIZEREQUEST

  # @@protoc_insertion_point(class_scope:Sanguo.protocol.prize.PrizeRequest)

class PrizeResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PRIZERESPONSE

  # @@protoc_insertion_point(class_scope:Sanguo.protocol.prize.PrizeResponse)


# @@protoc_insertion_point(module_scope)
